title: "elementary Blog"
description: "We design and develop the fast, open, and privacy-respecting replacement for Windows and macOS"
permalink: /:title/
theme-color: "#702459"
gravatar: 0a8fe00dfeaeb95fe5ea132c758e4c1d

facebook: elementaryos
mastodon: elementary
reddit: elementaryos
twitter: elementary

authors:
  hodev:
    name: Hosein Mola
    description: "authors"
    gravatar: 0a8fe00dfeaeb95fe5ea132c758e4c1d # Gravatar md5 hash
  anonymous:
    name: "Unknown Author"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 10
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
